name: Release Package to GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Node.js for GitHub Packages publish
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://npm.pkg.github.com'

      - name: Install dependencies and build
        run: npm install && npm run build

      - name: Verify package scope
        run: |
          PACKAGE_NAME=$(node -p "require('./package.json').name")
          if [[ ! "$PACKAGE_NAME" == "@"* ]]; then
            echo "Error: Package name '$PACKAGE_NAME' in package.json is not scoped."
            echo "It must be in the format '@owner/repository_name' or '@owner/package_name' to publish to GitHub Packages."
            echo "Please update your package.json."
            exit 1
          fi
          echo "Package name '$PACKAGE_NAME' is correctly scoped."
          
      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get package version
        id: package_version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.package_version.outputs.version }}
          name: Release v${{ steps.package_version.outputs.version }}
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}